// <auto-generated />
using System;
using EFCORELEARNING.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCORELEARNING.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250517064711_SeedDataEmployeeC#Base")]
    partial class SeedDataEmployeeCBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCORELEARNING.Models.Customer", b =>
                {
                    b.Property<int>("CurtomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurtomerId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ContactTitle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Region")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("State")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CurtomerId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("EFCORELEARNING.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime");

                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Hiredate")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Region")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("State")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TitleofCourtesy")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("mgrid")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Birthdate = new DateTime(1958, 12, 8, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            City = "تهران",
                            FirstName = "سحر",
                            Hiredate = new DateTime(2002, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "تقوی",
                            Region = "مرکز",
                            State = "تهران",
                            Title = "CEO",
                            TitleofCourtesy = "Ms."
                        },
                        new
                        {
                            EmployeeID = 2,
                            Birthdate = new DateTime(1962, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "تهران",
                            FirstName = "بهزاد",
                            Hiredate = new DateTime(2002, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "فکری",
                            Region = "مرکز",
                            State = "تهران",
                            Title = "Vice President, Sales",
                            TitleofCourtesy = "Mr.",
                            mgrid = 1
                        },
                        new
                        {
                            EmployeeID = 3,
                            Birthdate = new DateTime(1973, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "تهران",
                            FirstName = "علی",
                            Hiredate = new DateTime(2002, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "پایدار",
                            Region = "مرکز",
                            State = "تهران",
                            Title = "Sales Manager",
                            TitleofCourtesy = "Ms.",
                            mgrid = 2
                        },
                        new
                        {
                            EmployeeID = 4,
                            Birthdate = new DateTime(1947, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "پردیس",
                            FirstName = "زهره",
                            Hiredate = new DateTime(2003, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "تهرانی",
                            Region = "حومه",
                            State = "تهران",
                            Title = "Sales Representative",
                            TitleofCourtesy = "Ms.",
                            mgrid = 3
                        },
                        new
                        {
                            EmployeeID = 5,
                            Birthdate = new DateTime(1965, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "کرج",
                            FirstName = "کامران",
                            Hiredate = new DateTime(2003, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "اسماعیلی",
                            State = "البرز",
                            Title = "Sales Manager",
                            TitleofCourtesy = "Mr.",
                            mgrid = 2
                        },
                        new
                        {
                            EmployeeID = 6,
                            Birthdate = new DateTime(1958, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "کرج",
                            FirstName = "سعید",
                            Hiredate = new DateTime(2004, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "دهقان",
                            State = "البرز",
                            Title = "Sales Representative",
                            TitleofCourtesy = "Mr.",
                            mgrid = 5
                        },
                        new
                        {
                            EmployeeID = 7,
                            Birthdate = new DateTime(1970, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "کرج",
                            FirstName = "پیمان",
                            Hiredate = new DateTime(2002, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "سلامی",
                            State = "البرز",
                            Title = "Sales Representative",
                            mgrid = 5
                        },
                        new
                        {
                            EmployeeID = 8,
                            Birthdate = new DateTime(1968, 1, 9, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "کرج",
                            FirstName = "زهرا",
                            Hiredate = new DateTime(2004, 3, 11, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "یکتا",
                            Region = "مرکز",
                            State = "البرز",
                            Title = "Sales Representative",
                            TitleofCourtesy = "Ms.",
                            mgrid = 3
                        },
                        new
                        {
                            EmployeeID = 9,
                            Birthdate = new DateTime(1976, 1, 27, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "شهریار",
                            FirstName = "محمد رضا",
                            Hiredate = new DateTime(2004, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "زنده دل",
                            State = "تهران",
                            Title = "Sales Representative",
                            TitleofCourtesy = "Mr.",
                            mgrid = 5
                        });
                });

            modelBuilder.Entity("EFCORELEARNING.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<decimal>("Freight")
                        .HasColumnType("money");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ShipperID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("EFCORELEARNING.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric(4,3)");

                    b.Property<short>("Qty")
                        .HasColumnType("smallint");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("EFCORELEARNING.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<bool>("Discontinued")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.HasKey("ProductID");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("EFCORELEARNING.Models.Order", b =>
                {
                    b.HasOne("EFCORELEARNING.Models.Customer", "CustomerOfOrder")
                        .WithMany("OrdersOfCustomer")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EFCORELEARNING.Models.Employee", "EmployeeOfOrder")
                        .WithMany("OrdersOfEmployee")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerOfOrder");

                    b.Navigation("EmployeeOfOrder");
                });

            modelBuilder.Entity("EFCORELEARNING.Models.OrderDetail", b =>
                {
                    b.HasOne("EFCORELEARNING.Models.Order", "OrderOfOrderDetail")
                        .WithMany("ListOfOrderDetailsOfOrder")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCORELEARNING.Models.Product", "ProductOfOrderDetail")
                        .WithMany("ListOfOrderDetailsOfProduct")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderOfOrderDetail");

                    b.Navigation("ProductOfOrderDetail");
                });

            modelBuilder.Entity("EFCORELEARNING.Models.Customer", b =>
                {
                    b.Navigation("OrdersOfCustomer");
                });

            modelBuilder.Entity("EFCORELEARNING.Models.Employee", b =>
                {
                    b.Navigation("OrdersOfEmployee");
                });

            modelBuilder.Entity("EFCORELEARNING.Models.Order", b =>
                {
                    b.Navigation("ListOfOrderDetailsOfOrder");
                });

            modelBuilder.Entity("EFCORELEARNING.Models.Product", b =>
                {
                    b.Navigation("ListOfOrderDetailsOfProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
